# Generated by Django 4.1.2 on 2022-11-05 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('color', models.CharField(max_length=200)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs_dam', to='dogs.dog')),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.kennel')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs_sire', to='dogs.dog')),
            ],
        ),
        migrations.CreateModel(
            name='ColorGenetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('aAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('eAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('bAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('dAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('sAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('mAlele', models.CharField(blank=True, max_length=20, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
        ),
    ]
