# Generated by Django 4.1.2 on 2023-10-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_wallet_litter_dog_litterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='litterID',
        ),
    ]
