# Generated by Django 4.1.2 on 2023-10-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_litterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litter',
            name='litterId',
        ),
    ]
